#version: 0.0
#os: linux
#files:
#  - source: /
#    destination: /home/ubuntu/deployment
#hooks:
#  BeforeInstall:
#    - location: scripts/env.sh
#      timeout: 300
#      runas: ubuntu
#  AfterInstall:
#    - location: scripts/deploy.sh
#      timeout: 300
#      runas: ubuntu