version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/deployment
hooks:
  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 300
      runas: ubuntu
      environment:
        ECR_REGISTRY: "{{ECR_REGISTRY}}"
        ECR_REPOSITORY: "{{ECR_REPOSITORY}}"